travis:
  secure:
    BINSTAR_TOKEN: OW9Uy3TP1oxUPY3LvSvhYpRaQuB2w76Utst1+bKhwRfPdJFso9kSAl3pSeQtec8LKhfLD8jfNJIx68hkzcha5aOVeedOhs66oFdogeXQ+GCLYZe6cZbjcWhKIQXVmIfMY+hrnwL4bvpdFuG7qF9/3CEihiFVc9q/o/X/JjJgL3cboap++E4vwuf5zDq8qR2smbWzBkNYu0sTKZJqVHNGy7nov2fqj3LNLzuAAvNXVd0t/43VGiOmJzlj7mRHMcffI5iFMEkCZiqZbTCz8ti2I6cNToWW6yONUtN+AD2AyOVpUzyQLsVI9gfHH3J5WOk9e5aYZG498XAI9awFdxxCyyR41ZGfT29HS1czU/mo++xmFxNdRGDF9GeiACi/S3K/iN6cXwPjXu7GNnmKH+bk29kuo7uOwmjqwtjU+H9jEfAiT8RLHNwcJ9+Te8XY1kMDKKxQne22hZ25R3QHrDI3Ea3hk41eUXjrqTc/UuhVNBIMVyPfW6ZH7VlOGjzWAFtVclRKpkCm6QM6dh5rljmRSeikeAKL81WngQXZoXwJcQ+bk+BEQ7Dvj0wViylpMaRZr3AXuDJJgfJ5xKpa6xGLlWHL3fCsvdwP+2SqZ2UBMyQSas8dQ9JlQd6WqBAhnp3aEPb2Y9N+uKXksUodhrGx1xZpbMHDxzprpzuaKIuICXY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
